import type { OrganizationalState } from "@/lib/domain/types";
import { deterministicAlexisEngine } from "@/lib/alexis/engine";
import { Panel } from "@/components/ui";

/**
 * Always-visible executive briefing, generated by asking Alexis the same
 * question a user could ask interactively — proves the briefing is
 * state-derived, not a separate hard-coded summary.
 */
export function ExecutiveBriefing({ state }: { state: OrganizationalState }) {
  const { answer } = deterministicAlexisEngine.ask("give me an executive briefing", state);

  return (
    <Panel eyebrow="Alexis" title="Executive Briefing" className="border-poa-accent/30">
      <p className="text-sm leading-relaxed text-poa-text">{answer}</p>
    </Panel>
  );
}
